# Funding for Glanvu
# Adds a "Sponsor" button to the repository on GitHub.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: juanyque
ko_fi: juanyque
